language: rust
os: windows
cache: cargo
script:
- cargo build --release
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "$TRAVIS_BUILD_DIR/target/release/rublog"
  skip_cleanup: true
  on:
    tags: true
