language: rust
os: windows
cache: cargo
script:
- cargo build --release
before_deploy:
  - cp target/release/rublog.exe rublog.exe
  - 7z a rublog_$TRAVIS_TAG.zip rublog.exe template
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "$TRAVIS_BUILD_DIR/target/release/rublog.exe"
  skip_cleanup: true
  on:
    tags: true
